spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: h2
    password: h2
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8181